- id: check-pinned-deps-for-needed-upgrade
  name: check if the pinned dependencies need to be upgraded
  entry: check-pinned-deps
  language: python
  additional_dependencies: [packaging, toml]

- id: validate-localstack-openapi-spec
  name: ensure LocalStack OpenAPI specification is valid
  entry: validate-openapi-spec
  language: python
  additional_dependencies: [localstack, localstack_ext, openapi_spec_validator]
